### ISSUE TITLE
Stellar Mediatation not added to Serenity

### ISSUE THREAD

**Issue by Asgmel** [ssiatkowski/degens-idle#17]
Hey! I think i found a bug with stellar meditation, as the tooltip says it should be added to all resources, and it shows up when you hover over serenity. But the multiplier itself is never added to the actual serenity per second you earn. Ref, screenshots:

My serenity gained per second and multiplier tooltip
![Serenity](https://github.com/user-attachments/assets/982500a5-dab0-4c57-ac08-cdae1b86fb04)

Calculation without stellar meditation
![calculation_no_mult](https://github.com/user-attachments/assets/8b3ca99c-bfcb-482e-96fa-29c42afe247e)

Calculation with stellar meditation
![calculation_with_mult](https://github.com/user-attachments/assets/44090720-4a40-4a77-8405-d5b958d03b0a)

**Comment by ssiatkowski** [comment]
fixed by correcting description
